In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# 2. Reading Data
train_df = pd.read_csv('train.csv')

/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_9798/1154620188.py:11: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv('train.csv')

In [2]:
train_df.head()

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [4]:
train_df.duplicated().sum()

0

In [ ]:
test_df.duplicated().sum()

In [ ]:
# List of columns you want to plot
columns_to_plot = ['Month', 'Occupation', 'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour', 'Credit_Score']

# Creating a countplot for each column
for column in columns_to_plot:
    plt.figure(figsize=(8, 3))  # Adjust figure size as needed
    sns.countplot(x=column, data=train_df, palette="mako")
    plt.xticks(rotation=45)  # Rotate x-axis labels to avoid overlap, adjust as needed
    plt.title(f'Count Plot for {column}')
    plt.show()

In [ ]:
train_df['Credit_Mix'].value_counts()

In [ ]:
sns.distplot(train_df['Monthly_Inhand_Salary']);

In [ ]:
train_df['Type_of_Loan'].value_counts().head(10)

In [ ]:

sns.histplot(train_df['Num_Bank_Accounts'], kde=True)

In [ ]:

sns.histplot(train_df['Num_Credit_Card'], kde=True)

In [ ]:
sns.histplot(train_df['Interest_Rate'], kde=True)

In [ ]:
sns.histplot(train_df['Delay_from_due_date'], kde=True)

In [ ]:
sns.histplot(train_df['Num_Credit_Inquiries'], kde=True)

In [ ]:
sns.histplot(train_df['Credit_Utilization_Ratio'], kde=True)

In [ ]:
sns.histplot(train_df['Total_EMI_per_month'], kde=True)

In [3]:
#deleting the colomns which are of no use
train_df.drop(['ID', 'Name', 'SSN'], axis=1, inplace = True)

In [4]:
# List of columns to convert from object to numerical data type
columns_to_convert = ['Age', 'Annual_Income', 'Num_of_Loan', 
                      'Num_of_Delayed_Payment', 'Changed_Credit_Limit', 
                      'Amount_invested_monthly', 'Outstanding_Debt', 
                       'Monthly_Balance']

# Convert columns to numeric, coerce errors for now
for column in columns_to_convert:
    # Using pandas to_numeric() with 'coerce' to handle errors by setting invalid parsing as NaN
    train_df[column] = pd.to_numeric(train_df[column], errors='coerce')

In [5]:
# Delete rows where 'Occupation' contains underscores
train_df = train_df[~train_df['Occupation'].str.contains('_')]

In [6]:
train_df['Credit_Mix'].value_counts()

Credit_Mix
Standard    31495
Good        21086
_           17520
Bad         16605
Name: count, dtype: int64

In [7]:
# Find the mode of the 'Credit_Mix' column
mode_value = train_df['Credit_Score'].mode()[0]

In [10]:
mode_value

'Standard'

In [8]:

# Replace underscores with the mode value in the 'Credit_Mix' column
train_df['Credit_Mix'] = train_df['Credit_Mix'].replace('_', mode_value)

In [ ]:
train_df['Credit_Mix'].value_counts()

In [9]:
for i in train_df['Type_of_Loan'].value_counts().head(9).index[1:] : 
    train_df[i] = train_df['Type_of_Loan'].str.contains(i)

del train_df['Type_of_Loan']

In [10]:
train_df['Num_Credit_Card'].replace(0,1,inplace=True)

In [11]:
def History_age(age):
    try : 
        years = int("".join(re.findall('[0-9]',''.join(age.split("and")[0]))))
        month = int("".join(re.findall('[0-9]',''.join(age.split("and")[1]))))
        return years*12 + month
    except :
        return np.nan

In [ ]:
train_df['Age'].head(10)

In [12]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86706 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               86706 non-null  object
 1   Month                     86706 non-null  object
 2   Age                       82402 non-null  float64
 3   Occupation                86706 non-null  object
 4   Annual_Income             80657 non-null  float64
 5   Monthly_Inhand_Salary     73672 non-null  float64
 6   Num_Bank_Accounts         86706 non-null  int64
 7   Num_Credit_Card           86706 non-null  int64
 8   Interest_Rate             86706 non-null  int64
 9   Num_of_Loan               82616 non-null  float64
 10  Delay_from_due_date       86706 non-null  int64
 11  Num_of_Delayed_Payment    78301 non-null  float64
 12  Changed_Credit_Limit      84898 non-null  float64
 13  Num_Credit_Inquiries      84993 non-null  float64
 14  Credit_Mix                86706 non-null  object
 15  Outstanding_Debt          85855 non-null  float64
 16  Credit_Utilization_Ratio  86706 non-null  float64
 17  Credit_History_Age        78881 non-null  object
 18  Payment_of_Min_Amount     86706 non-null  object
 19  Total_EMI_per_month       86706 non-null  float64
 20  Amount_invested_monthly   79120 non-null  float64
 21  Payment_Behaviour         86706 non-null  object
 22  Monthly_Balance           85635 non-null  float64
 23  Credit_Score              86706 non-null  object
 24  Debt Consolidation Loan   76901 non-null  object
 25  Personal Loan             76901 non-null  object
 26  Student Loan              76901 non-null  object
 27  Credit-Builder Loan       76901 non-null  object
 28  Payday Loan               76901 non-null  object
 29  Mortgage Loan             76901 non-null  object
 30  Auto Loan                 76901 non-null  object
 31  Home Equity Loan          76901 non-null  object
dtypes: float64(12), int64(4), object(16)
memory usage: 21.8+ MB

In [ ]:
train_df['Credit_History_Age'].head(10)

In [13]:
train_df['Payment_of_Min_Amount'].replace("NM","No",inplace=True)

In [ ]:
train_df['Payment_of_Min_Amount'].value_counts()

In [ ]:
train_df['Payment_Behaviour'].value_counts()

In [14]:
train_df['Payment_Behaviour']= train_df['Payment_Behaviour'].replace("!@9#%8",np.nan)

In [ ]:
train_df['Payment_Behaviour'].value_counts()

In [ ]:
train_df['Occupation'].value_counts()

In [ ]:
train_df['Personal Loan'].value_counts()

In [ ]:
train_df.info()

In [15]:
# Edit Columns from bool to int 
for col in list(train_df.columns[-8:]):
    train_df[col] = train_df[col].astype(float)
IDs = 1 
for ID in train_df['Customer_ID'].unique() :
    train_df['Customer_ID'] = train_df['Customer_ID'].replace(ID,IDs)
    IDs += 1

In [16]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86706 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               86706 non-null  int64
 1   Month                     86706 non-null  object
 2   Age                       82402 non-null  float64
 3   Occupation                86706 non-null  object
 4   Annual_Income             80657 non-null  float64
 5   Monthly_Inhand_Salary     73672 non-null  float64
 6   Num_Bank_Accounts         86706 non-null  int64
 7   Num_Credit_Card           86706 non-null  int64
 8   Interest_Rate             86706 non-null  int64
 9   Num_of_Loan               82616 non-null  float64
 10  Delay_from_due_date       86706 non-null  int64
 11  Num_of_Delayed_Payment    78301 non-null  float64
 12  Changed_Credit_Limit      84898 non-null  float64
 13  Num_Credit_Inquiries      84993 non-null  float64
 14  Credit_Mix                86706 non-null  object
 15  Outstanding_Debt          85855 non-null  float64
 16  Credit_Utilization_Ratio  86706 non-null  float64
 17  Credit_History_Age        78881 non-null  object
 18  Payment_of_Min_Amount     86706 non-null  object
 19  Total_EMI_per_month       86706 non-null  float64
 20  Amount_invested_monthly   79120 non-null  float64
 21  Payment_Behaviour         80113 non-null  object
 22  Monthly_Balance           85635 non-null  float64
 23  Credit_Score              86706 non-null  object
 24  Debt Consolidation Loan   76901 non-null  float64
 25  Personal Loan             76901 non-null  float64
 26  Student Loan              76901 non-null  float64
 27  Credit-Builder Loan       76901 non-null  float64
 28  Payday Loan               76901 non-null  float64
 29  Mortgage Loan             76901 non-null  float64
 30  Auto Loan                 76901 non-null  float64
 31  Home Equity Loan          76901 non-null  float64
dtypes: float64(20), int64(5), object(7)
memory usage: 21.8+ MB

In [17]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)

In [18]:
Numericals = train_df.select_dtypes(exclude='object').columns[1:]
Numericals

Index(['Age', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Total_EMI_per_month', 'Amount_invested_monthly', 'Monthly_Balance',
       'Debt Consolidation Loan', 'Personal Loan', 'Student Loan',
       'Credit-Builder Loan', 'Payday Loan', 'Mortgage Loan', 'Auto Loan',
       'Home Equity Loan'],
      dtype='object')

In [ ]:
train_df.info()

In [19]:
#Imputing Missing Values in Customer ID and Numerical Columns

for col in Numericals[1:]:
    imputer.fit(train_df[['Customer_ID',col]])
    train_df[['Customer_ID',col]] = imputer.transform(train_df[['Customer_ID',col]])

In [ ]:
train_df.info()

In [1]:
#Imputing Missing Values in Payment Behavior Using Most Frequent Strategy

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")
imputer.fit(train_df[['Payment_Behaviour']])
train_df[['Payment_Behaviour']] = imputer.transform(train_df[['Payment_Behaviour']])

NameError: name 'train_df' is not defined

In [ ]:
train_df.info()

In [21]:
#Imputing Missing Values in Credit History Age Using Most Frequent Strategy

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")
imputer.fit(train_df[['Credit_History_Age']])
train_df[['Credit_History_Age']] = imputer.transform(train_df[['Credit_History_Age']])

In [ ]:
train_df.info()

In [23]:

!pip install datasist
from datasist.structdata import detect_outliers

Requirement already satisfied: datasist in ./anaconda3/lib/python3.11/site-packages (1.5.3)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.11/site-packages (from datasist) (2.0.3)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.11/site-packages (from datasist) (3.7.2)
Requirement already satisfied: seaborn in ./anaconda3/lib/python3.11/site-packages (from datasist) (0.12.2)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.11/site-packages (from datasist) (1.24.3)
Requirement already satisfied: jupyter in ./anaconda3/lib/python3.11/site-packages (from datasist) (1.0.0)
Requirement already satisfied: scikit-learn in ./anaconda3/lib/python3.11/site-packages (from datasist) (1.3.0)
Requirement already satisfied: nltk in ./anaconda3/lib/python3.11/site-packages (from datasist) (3.8.1)
Requirement already satisfied: Joblib in ./anaconda3/lib/python3.11/site-packages (from datasist) (1.2.0)
Requirement already satisfied: notebook in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (6.5.4)
Requirement already satisfied: qtconsole in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (5.4.2)
Requirement already satisfied: jupyter-console in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (6.6.3)
Requirement already satisfied: nbconvert in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (6.5.4)
Requirement already satisfied: ipykernel in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (6.25.0)
Requirement already satisfied: ipywidgets in ./anaconda3/lib/python3.11/site-packages (from jupyter->datasist) (8.0.4)
Requirement already satisfied: contourpy>=1.0.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (1.0.5)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (1.4.4)
Requirement already satisfied: packaging>=20.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (23.1)
Requirement already satisfied: pillow>=6.2.0 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in ./anaconda3/lib/python3.11/site-packages (from matplotlib->datasist) (2.8.2)
Requirement already satisfied: click in ./anaconda3/lib/python3.11/site-packages (from nltk->datasist) (8.0.4)
Requirement already satisfied: regex>=2021.8.3 in ./anaconda3/lib/python3.11/site-packages (from nltk->datasist) (2022.7.9)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.11/site-packages (from nltk->datasist) (4.65.0)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.11/site-packages (from pandas->datasist) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in ./anaconda3/lib/python3.11/site-packages (from pandas->datasist) (2023.3)
Requirement already satisfied: scipy>=1.5.0 in ./anaconda3/lib/python3.11/site-packages (from scikit-learn->datasist) (1.11.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in ./anaconda3/lib/python3.11/site-packages (from scikit-learn->datasist) (2.2.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->datasist) (1.16.0)
Requirement already satisfied: appnope in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (0.1.2)
Requirement already satisfied: comm>=0.1.1 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (0.1.2)
Requirement already satisfied: debugpy>=1.6.5 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (8.15.0)
Requirement already satisfied: jupyter-client>=6.1.12 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (7.4.9)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (5.3.0)
Requirement already satisfied: matplotlib-inline>=0.1 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (0.1.6)
Requirement already satisfied: nest-asyncio in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (1.5.6)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (5.9.0)
Requirement already satisfied: pyzmq>=20 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (23.2.0)
Requirement already satisfied: tornado>=6.1 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (6.3.2)
Requirement already satisfied: traitlets>=5.4.0 in ./anaconda3/lib/python3.11/site-packages (from ipykernel->jupyter->datasist) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0 in ./anaconda3/lib/python3.11/site-packages (from ipywidgets->jupyter->datasist) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in ./anaconda3/lib/python3.11/site-packages (from ipywidgets->jupyter->datasist) (3.0.5)
Requirement already satisfied: prompt-toolkit>=3.0.30 in ./anaconda3/lib/python3.11/site-packages (from jupyter-console->jupyter->datasist) (3.0.36)
Requirement already satisfied: pygments in ./anaconda3/lib/python3.11/site-packages (from jupyter-console->jupyter->datasist) (2.15.1)
Requirement already satisfied: lxml in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (4.9.3)
Requirement already satisfied: beautifulsoup4 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (4.12.2)
Requirement already satisfied: bleach in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (4.1.0)
Requirement already satisfied: defusedxml in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (0.7.1)
Requirement already satisfied: entrypoints>=0.2.2 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (0.4)
Requirement already satisfied: jinja2>=3.0 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (3.1.2)
Requirement already satisfied: jupyterlab-pygments in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (2.1.1)
Requirement already satisfied: mistune<2,>=0.8.1 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (0.8.4)
Requirement already satisfied: nbclient>=0.5.0 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (0.5.13)
Requirement already satisfied: nbformat>=5.1 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (5.9.2)
Requirement already satisfied: pandocfilters>=1.4.1 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (1.5.0)
Requirement already satisfied: tinycss2 in ./anaconda3/lib/python3.11/site-packages (from nbconvert->jupyter->datasist) (1.2.1)
Requirement already satisfied: argon2-cffi in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (21.3.0)
Requirement already satisfied: ipython-genutils in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (0.2.0)
Requirement already satisfied: Send2Trash>=1.8.0 in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (1.8.0)
Requirement already satisfied: terminado>=0.8.3 in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (0.17.1)
Requirement already satisfied: prometheus-client in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (0.14.1)
Requirement already satisfied: nbclassic>=0.4.7 in ./anaconda3/lib/python3.11/site-packages (from notebook->jupyter->datasist) (0.5.5)
Requirement already satisfied: qtpy>=2.0.1 in ./anaconda3/lib/python3.11/site-packages (from qtconsole->jupyter->datasist) (2.2.0)
Requirement already satisfied: backcall in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (0.2.0)
Requirement already satisfied: decorator in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (5.1.1)
Requirement already satisfied: jedi>=0.16 in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (0.18.1)
Requirement already satisfied: pickleshare in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (0.7.5)
Requirement already satisfied: stack-data in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (0.2.0)
Requirement already satisfied: pexpect>4.3 in ./anaconda3/lib/python3.11/site-packages (from ipython>=7.23.1->ipykernel->jupyter->datasist) (4.8.0)
Requirement already satisfied: platformdirs>=2.5 in ./anaconda3/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter->datasist) (3.10.0)
Requirement already satisfied: jupyter-server>=1.8 in ./anaconda3/lib/python3.11/site-packages (from nbclassic>=0.4.7->notebook->jupyter->datasist) (1.23.4)
Requirement already satisfied: notebook-shim>=0.1.0 in ./anaconda3/lib/python3.11/site-packages (from nbclassic>=0.4.7->notebook->jupyter->datasist) (0.2.2)
Requirement already satisfied: fastjsonschema in ./anaconda3/lib/python3.11/site-packages (from nbformat>=5.1->nbconvert->jupyter->datasist) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in ./anaconda3/lib/python3.11/site-packages (from nbformat>=5.1->nbconvert->jupyter->datasist) (4.17.3)
Requirement already satisfied: wcwidth in ./anaconda3/lib/python3.11/site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter->datasist) (0.2.5)
Requirement already satisfied: ptyprocess in ./anaconda3/lib/python3.11/site-packages (from terminado>=0.8.3->notebook->jupyter->datasist) (0.7.0)
Requirement already satisfied: argon2-cffi-bindings in ./anaconda3/lib/python3.11/site-packages (from argon2-cffi->notebook->jupyter->datasist) (21.2.0)
Requirement already satisfied: soupsieve>1.2 in ./anaconda3/lib/python3.11/site-packages (from beautifulsoup4->nbconvert->jupyter->datasist) (2.4)
Requirement already satisfied: webencodings in ./anaconda3/lib/python3.11/site-packages (from bleach->nbconvert->jupyter->datasist) (0.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./anaconda3/lib/python3.11/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter->datasist) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in ./anaconda3/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter->datasist) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in ./anaconda3/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1->nbconvert->jupyter->datasist) (0.18.0)
Requirement already satisfied: anyio<4,>=3.1.0 in ./anaconda3/lib/python3.11/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter->datasist) (3.5.0)
Requirement already satisfied: websocket-client in ./anaconda3/lib/python3.11/site-packages (from jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter->datasist) (0.58.0)
Requirement already satisfied: cffi>=1.0.1 in ./anaconda3/lib/python3.11/site-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter->datasist) (1.15.1)
Requirement already satisfied: executing in ./anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter->datasist) (0.8.3)
Requirement already satisfied: asttokens in ./anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter->datasist) (2.0.5)
Requirement already satisfied: pure-eval in ./anaconda3/lib/python3.11/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter->datasist) (0.2.2)
Requirement already satisfied: idna>=2.8 in ./anaconda3/lib/python3.11/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter->datasist) (3.4)
Requirement already satisfied: sniffio>=1.1 in ./anaconda3/lib/python3.11/site-packages (from anyio<4,>=3.1.0->jupyter-server>=1.8->nbclassic>=0.4.7->notebook->jupyter->datasist) (1.2.0)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.11/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter->datasist) (2.21)

In [24]:
## Replace Outliers with median
for col in Numericals:
    outliers_indices = detect_outliers(train_df, 0, [col])
    median = train_df[col].median()
    
    # Ensure indices are within the current DataFrame index range
    valid_indices = [idx for idx in outliers_indices if idx < len(train_df)]
    
    train_df[col].iloc[valid_indices] = median

/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median
/var/folders/b_/81pnbcn12j9_jgbwb9mnrym00000gn/T/ipykernel_10415/2196755136.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df[col].iloc[valid_indices] = median

In [ ]:
train_df.info()

In [ ]:
train_df.select_dtypes(include="object")

In [ ]:
train_df['Credit_Score'].value_counts()

In [ ]:
train_df['Payment_Behaviour'].value_counts()

In [ ]:
train_df['Payment_of_Min_Amount'].value_counts()

In [ ]:
train_df['Credit_History_Age'].value_counts()

In [ ]:
train_df['Credit_Mix'].value_counts()

In [ ]:
train_df['Occupation'].value_counts()

In [ ]:
train_df['Month'].value_counts()

In [ ]:
train_df.info()

In [25]:
credit_score_mapping = {'Poor': 0, 'Standard': 1, 'Good': 2}
train_df['Credit_Score'] = train_df['Credit_Score'].map(credit_score_mapping)

In [26]:
payment_behaviour_mapping = {label: idx for idx, label in enumerate(train_df['Payment_Behaviour'].unique())}
train_df['Payment_Behaviour'] = train_df['Payment_Behaviour'].map(payment_behaviour_mapping)

In [27]:
train_df['Payment_of_Min_Amount'] = train_df['Payment_of_Min_Amount'].map({'Yes': 1, 'No': 0})

In [28]:
credit_mix_mapping = {'Bad': 0, 'Standard': 1, 'Good': 2}
train_df['Credit_Mix'] = train_df['Credit_Mix'].map(credit_mix_mapping)

In [29]:
occupation_mapping = {label: idx for idx, label in enumerate(train_df['Occupation'].unique())}
train_df['Occupation'] = train_df['Occupation'].map(occupation_mapping)

In [30]:
month_mapping = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 'July': 7, 'August': 8}
train_df['Month'] = train_df['Month'].map(month_mapping)

In [31]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86706 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               86706 non-null  float64
 1   Month                     86706 non-null  int64
 2   Age                       82402 non-null  float64
 3   Occupation                86706 non-null  int64
 4   Annual_Income             86706 non-null  float64
 5   Monthly_Inhand_Salary     86706 non-null  float64
 6   Num_Bank_Accounts         86706 non-null  float64
 7   Num_Credit_Card           86706 non-null  float64
 8   Interest_Rate             86706 non-null  float64
 9   Num_of_Loan               86706 non-null  float64
 10  Delay_from_due_date       86706 non-null  float64
 11  Num_of_Delayed_Payment    86706 non-null  float64
 12  Changed_Credit_Limit      86706 non-null  float64
 13  Num_Credit_Inquiries      86706 non-null  float64
 14  Credit_Mix                86706 non-null  int64
 15  Outstanding_Debt          86706 non-null  float64
 16  Credit_Utilization_Ratio  86706 non-null  float64
 17  Credit_History_Age        86706 non-null  object
 18  Payment_of_Min_Amount     86706 non-null  int64
 19  Total_EMI_per_month       86706 non-null  float64
 20  Amount_invested_monthly   86706 non-null  float64
 21  Payment_Behaviour         86706 non-null  int64
 22  Monthly_Balance           86706 non-null  float64
 23  Credit_Score              86706 non-null  int64
 24  Debt Consolidation Loan   86706 non-null  float64
 25  Personal Loan             86706 non-null  float64
 26  Student Loan              86706 non-null  float64
 27  Credit-Builder Loan       86706 non-null  float64
 28  Payday Loan               86706 non-null  float64
 29  Mortgage Loan             86706 non-null  float64
 30  Auto Loan                 86706 non-null  float64
 31  Home Equity Loan          86706 non-null  float64
dtypes: float64(25), int64(6), object(1)
memory usage: 21.8+ MB

In [32]:
list1 = train_df['Credit_History_Age'].to_list()

In [33]:
list1

['22 Years and 1 Months',
 '17 Years and 11 Months',
 '22 Years and 3 Months',
 '22 Years and 4 Months',
 '22 Years and 5 Months',
 '22 Years and 6 Months',
 '22 Years and 7 Months',
 '17 Years and 11 Months',
 '26 Years and 8 Months',
 '26 Years and 9 Months',
 '26 Years and 10 Months',
 '26 Years and 11 Months',
 '27 Years and 0 Months',
 '27 Years and 1 Months',
 '27 Years and 2 Months',
 '17 Years and 10 Months',
 '17 Years and 11 Months',
 '18 Years and 2 Months',
 '18 Years and 3 Months',
 '18 Years and 4 Months',
 '17 Years and 3 Months',
 '17 Years and 4 Months',
 '17 Years and 5 Months',
 '17 Years and 6 Months',
 '17 Years and 7 Months',
 '17 Years and 9 Months',
 '17 Years and 10 Months',
 '30 Years and 8 Months',
 '30 Years and 9 Months',
 '30 Years and 10 Months',
 '30 Years and 11 Months',
 '31 Years and 0 Months',
 '31 Years and 1 Months',
 '31 Years and 2 Months',
 '31 Years and 3 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '32 Years and 2 Months',
 '32 Years and 3 Months',
 '17 Years and 11 Months',
 '32 Years and 5 Months',
 '32 Years and 6 Months',
 '30 Years and 7 Months',
 '30 Years and 8 Months',
 '30 Years and 9 Months',
 '30 Years and 10 Months',
 '30 Years and 11 Months',
 '31 Years and 0 Months',
 '31 Years and 1 Months',
 '31 Years and 2 Months',
 '21 Years and 4 Months',
 '21 Years and 5 Months',
 '21 Years and 6 Months',
 '21 Years and 7 Months',
 '21 Years and 8 Months',
 '21 Years and 9 Months',
 '21 Years and 10 Months',
 '21 Years and 11 Months',
 '17 Years and 11 Months',
 '26 Years and 6 Months',
 '26 Years and 7 Months',
 '26 Years and 8 Months',
 '26 Years and 9 Months',
 '17 Years and 11 Months',
 '26 Years and 11 Months',
 '27 Years and 0 Months',
 '19 Years and 2 Months',
 '19 Years and 3 Months',
 '19 Years and 5 Months',
 '19 Years and 6 Months',
 '19 Years and 7 Months',
 '19 Years and 8 Months',
 '17 Years and 11 Months',
 '25 Years and 5 Months',
 '25 Years and 6 Months',
 '25 Years and 7 Months',
 '25 Years and 8 Months',
 '25 Years and 9 Months',
 '25 Years and 10 Months',
 '25 Years and 11 Months',
 '26 Years and 0 Months',
 '26 Years and 10 Months',
 '26 Years and 11 Months',
 '27 Years and 0 Months',
 '27 Years and 1 Months',
 '27 Years and 2 Months',
 '27 Years and 3 Months',
 '27 Years and 4 Months',
 '27 Years and 5 Months',
 '8 Years and 11 Months',
 '9 Years and 0 Months',
 '9 Years and 1 Months',
 '9 Years and 2 Months',
 '9 Years and 3 Months',
 '9 Years and 4 Months',
 '17 Years and 11 Months',
 '9 Years and 6 Months',
 '18 Years and 2 Months',
 '18 Years and 3 Months',
 '18 Years and 4 Months',
 '18 Years and 5 Months',
 '18 Years and 6 Months',
 '17 Years and 11 Months',
 '18 Years and 8 Months',
 '18 Years and 9 Months',
 '16 Years and 10 Months',
 '16 Years and 11 Months',
 '17 Years and 0 Months',
 '17 Years and 1 Months',
 '17 Years and 2 Months',
 '17 Years and 3 Months',
 '17 Years and 4 Months',
 '17 Years and 5 Months',
 '29 Years and 2 Months',
 '29 Years and 3 Months',
 '29 Years and 4 Months',
 '17 Years and 11 Months',
 '29 Years and 6 Months',
 '17 Years and 11 Months',
 '29 Years and 8 Months',
 '29 Years and 9 Months',
 '6 Years and 5 Months',
 '6 Years and 6 Months',
 '6 Years and 7 Months',
 '6 Years and 8 Months',
 '6 Years and 9 Months',
 '6 Years and 10 Months',
 '6 Years and 11 Months',
 '7 Years and 0 Months',
 '27 Years and 2 Months',
 '27 Years and 3 Months',
 '27 Years and 4 Months',
 '27 Years and 5 Months',
 '27 Years and 6 Months',
 '27 Years and 7 Months',
 '27 Years and 8 Months',
 '27 Years and 9 Months',
 '18 Years and 2 Months',
 '18 Years and 3 Months',
 '17 Years and 11 Months',
 '18 Years and 5 Months',
 '17 Years and 11 Months',
 '18 Years and 8 Months',
 '18 Years and 9 Months',
 '19 Years and 3 Months',
 '19 Years and 4 Months',
 '19 Years and 5 Months',
 '19 Years and 6 Months',
 '19 Years and 7 Months',
 '19 Years and 9 Months',
 '19 Years and 10 Months',
 '32 Years and 9 Months',
 '32 Years and 10 Months',
 '32 Years and 11 Months',
 '33 Years and 0 Months',
 '33 Years and 1 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '33 Years and 4 Months',
 '12 Years and 3 Months',
 '12 Years and 4 Months',
 '12 Years and 5 Months',
 '12 Years and 7 Months',
 '12 Years and 8 Months',
 '17 Years and 11 Months',
 '12 Years and 10 Months',
 '17 Years and 11 Months',
 '12 Years and 3 Months',
 '12 Years and 4 Months',
 '12 Years and 5 Months',
 '12 Years and 6 Months',
 '12 Years and 7 Months',
 '12 Years and 8 Months',
 '12 Years and 9 Months',
 '17 Years and 10 Months',
 '18 Years and 1 Months',
 '18 Years and 2 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '18 Years and 5 Months',
 '13 Years and 8 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '13 Years and 11 Months',
 '14 Years and 1 Months',
 '14 Years and 2 Months',
 '14 Years and 3 Months',
 '19 Years and 2 Months',
 '19 Years and 3 Months',
 '19 Years and 4 Months',
 '19 Years and 5 Months',
 '19 Years and 6 Months',
 '19 Years and 7 Months',
 '19 Years and 8 Months',
 '19 Years and 9 Months',
 '30 Years and 3 Months',
 '30 Years and 4 Months',
 '30 Years and 6 Months',
 '30 Years and 7 Months',
 '30 Years and 8 Months',
 '17 Years and 11 Months',
 '30 Years and 10 Months',
 '17 Years and 11 Months',
 '8 Years and 9 Months',
 '8 Years and 10 Months',
 '8 Years and 11 Months',
 '9 Years and 0 Months',
 '9 Years and 1 Months',
 '17 Years and 11 Months',
 '9 Years and 3 Months',
 '18 Years and 3 Months',
 '18 Years and 4 Months',
 '18 Years and 5 Months',
 '18 Years and 6 Months',
 '18 Years and 7 Months',
 '18 Years and 8 Months',
 '18 Years and 9 Months',
 '17 Years and 11 Months',
 '18 Years and 9 Months',
 '18 Years and 10 Months',
 '18 Years and 11 Months',
 '19 Years and 0 Months',
 '19 Years and 1 Months',
 '19 Years and 2 Months',
 '19 Years and 3 Months',
 '19 Years and 4 Months',
 '8 Years and 8 Months',
 '8 Years and 9 Months',
 '8 Years and 10 Months',
 '9 Years and 0 Months',
 '9 Years and 1 Months',
 '9 Years and 2 Months',
 '9 Years and 3 Months',
 '13 Years and 1 Months',
 '13 Years and 2 Months',
 '13 Years and 3 Months',
 '17 Years and 11 Months',
 '13 Years and 5 Months',
 '13 Years and 6 Months',
 '13 Years and 7 Months',
 '13 Years and 8 Months',
 '21 Years and 5 Months',
 '21 Years and 6 Months',
 '21 Years and 7 Months',
 '21 Years and 8 Months',
 '21 Years and 9 Months',
 '21 Years and 10 Months',
 '17 Years and 11 Months',
 '22 Years and 0 Months',
 '25 Years and 7 Months',
 '25 Years and 8 Months',
 '25 Years and 9 Months',
 '25 Years and 10 Months',
 '25 Years and 11 Months',
 '26 Years and 0 Months',
 '26 Years and 1 Months',
 '26 Years and 2 Months',
 '17 Years and 11 Months',
 '13 Years and 3 Months',
 '13 Years and 4 Months',
 '13 Years and 5 Months',
 '13 Years and 6 Months',
 '13 Years and 7 Months',
 '13 Years and 8 Months',
 '13 Years and 9 Months',
 '27 Years and 11 Months',
 '28 Years and 0 Months',
 '28 Years and 1 Months',
 '28 Years and 4 Months',
 '28 Years and 5 Months',
 '7 Years and 10 Months',
 '7 Years and 11 Months',
 '8 Years and 0 Months',
 '8 Years and 1 Months',
 '8 Years and 2 Months',
 '8 Years and 3 Months',
 '8 Years and 4 Months',
 '8 Years and 5 Months',
 '24 Years and 3 Months',
 '24 Years and 4 Months',
 '24 Years and 5 Months',
 '24 Years and 6 Months',
 '24 Years and 7 Months',
 '24 Years and 8 Months',
 '24 Years and 9 Months',
 '17 Years and 11 Months',
 '1 Years and 2 Months',
 '1 Years and 3 Months',
 '1 Years and 4 Months',
 '1 Years and 5 Months',
 '1 Years and 6 Months',
 '1 Years and 7 Months',
 '1 Years and 8 Months',
 '17 Years and 11 Months',
 '10 Years and 11 Months',
 '11 Years and 0 Months',
 '11 Years and 3 Months',
 '11 Years and 4 Months',
 '11 Years and 5 Months',
 '11 Years and 6 Months',
 '30 Years and 7 Months',
 '30 Years and 10 Months',
 '30 Years and 11 Months',
 '31 Years and 0 Months',
 '31 Years and 1 Months',
 '31 Years and 2 Months',
 '19 Years and 7 Months',
 '19 Years and 8 Months',
 '19 Years and 9 Months',
 '19 Years and 10 Months',
 '19 Years and 11 Months',
 '20 Years and 0 Months',
 '20 Years and 1 Months',
 '17 Years and 11 Months',
 '10 Years and 6 Months',
 '10 Years and 7 Months',
 '17 Years and 11 Months',
 '10 Years and 9 Months',
 '10 Years and 10 Months',
 '17 Years and 11 Months',
 '11 Years and 0 Months',
 '13 Years and 11 Months',
 '14 Years and 0 Months',
 '14 Years and 1 Months',
 '14 Years and 3 Months',
 '14 Years and 4 Months',
 '14 Years and 5 Months',
 '20 Years and 8 Months',
 '20 Years and 9 Months',
 '20 Years and 10 Months',
 '20 Years and 11 Months',
 '21 Years and 0 Months',
 '21 Years and 2 Months',
 '21 Years and 3 Months',
 '0 Years and 4 Months',
 '0 Years and 5 Months',
 '0 Years and 6 Months',
 '17 Years and 11 Months',
 '0 Years and 8 Months',
 '0 Years and 9 Months',
 '0 Years and 10 Months',
 '17 Years and 11 Months',
 '31 Years and 7 Months',
 '31 Years and 8 Months',
 '31 Years and 9 Months',
 '31 Years and 10 Months',
 '31 Years and 11 Months',
 '32 Years and 0 Months',
 '32 Years and 1 Months',
 '32 Years and 2 Months',
 '16 Years and 10 Months',
 '17 Years and 0 Months',
 '17 Years and 1 Months',
 '17 Years and 3 Months',
 '17 Years and 4 Months',
 '17 Years and 5 Months',
 '12 Years and 5 Months',
 '12 Years and 6 Months',
 '12 Years and 7 Months',
 '12 Years and 8 Months',
 '12 Years and 9 Months',
 '12 Years and 10 Months',
 '12 Years and 11 Months',
 '13 Years and 0 Months',
 '12 Years and 7 Months',
 '12 Years and 8 Months',
 '12 Years and 9 Months',
 '12 Years and 10 Months',
 '17 Years and 11 Months',
 '13 Years and 0 Months',
 '13 Years and 1 Months',
 '13 Years and 2 Months',
 '27 Years and 3 Months',
 '27 Years and 5 Months',
 '27 Years and 6 Months',
 '27 Years and 7 Months',
 '27 Years and 8 Months',
 '27 Years and 10 Months',
 '11 Years and 4 Months',
 '11 Years and 5 Months',
 '11 Years and 6 Months',
 '11 Years and 7 Months',
 '11 Years and 8 Months',
 '11 Years and 10 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '24 Years and 9 Months',
 '24 Years and 10 Months',
 '24 Years and 11 Months',
 '25 Years and 0 Months',
 '25 Years and 2 Months',
 '25 Years and 3 Months',
 '17 Years and 7 Months',
 '17 Years and 8 Months',
 '17 Years and 9 Months',
 '17 Years and 11 Months',
 '18 Years and 0 Months',
 '18 Years and 1 Months',
 '18 Years and 2 Months',
 '12 Years and 8 Months',
 '12 Years and 9 Months',
 '12 Years and 10 Months',
 '13 Years and 0 Months',
 '17 Years and 11 Months',
 '13 Years and 2 Months',
 '17 Years and 11 Months',
 '10 Years and 1 Months',
 '10 Years and 2 Months',
 '10 Years and 3 Months',
 '10 Years and 4 Months',
 '10 Years and 5 Months',
 '10 Years and 6 Months',
 '10 Years and 7 Months',
 '10 Years and 8 Months',
 '19 Years and 1 Months',
 '19 Years and 2 Months',
 '19 Years and 3 Months',
 '19 Years and 4 Months',
 '19 Years and 5 Months',
 '19 Years and 7 Months',
 '17 Years and 11 Months',
 '31 Years and 2 Months',
 '31 Years and 3 Months',
 '31 Years and 4 Months',
 '31 Years and 5 Months',
 '31 Years and 7 Months',
 '31 Years and 8 Months',
 '17 Years and 11 Months',
 '30 Years and 9 Months',
 '30 Years and 10 Months',
 '30 Years and 11 Months',
 '31 Years and 1 Months',
 '31 Years and 3 Months',
 '17 Years and 1 Months',
 '17 Years and 2 Months',
 '17 Years and 3 Months',
 '17 Years and 4 Months',
 '17 Years and 5 Months',
 '17 Years and 7 Months',
 '17 Years and 8 Months',
 '13 Years and 2 Months',
 '13 Years and 3 Months',
 '13 Years and 4 Months',
 '13 Years and 5 Months',
 '13 Years and 6 Months',
 '17 Years and 11 Months',
 '13 Years and 8 Months',
 '5 Years and 2 Months',
 '5 Years and 3 Months',
 '5 Years and 4 Months',
 '5 Years and 5 Months',
 '5 Years and 6 Months',
 '5 Years and 7 Months',
 '5 Years and 8 Months',
 '5 Years and 9 Months',
 '13 Years and 1 Months',
 '13 Years and 2 Months',
 '13 Years and 3 Months',
 '13 Years and 4 Months',
 '13 Years and 5 Months',
 '13 Years and 6 Months',
 '13 Years and 7 Months',
 '13 Years and 8 Months',
 '24 Years and 3 Months',
 '24 Years and 4 Months',
 '24 Years and 5 Months',
 '24 Years and 6 Months',
 '24 Years and 7 Months',
 '24 Years and 8 Months',
 '24 Years and 9 Months',
 '17 Years and 11 Months',
 '16 Years and 4 Months',
 '16 Years and 5 Months',
 '16 Years and 6 Months',
 '16 Years and 8 Months',
 '16 Years and 10 Months',
 '16 Years and 11 Months',
 '22 Years and 11 Months',
 '23 Years and 0 Months',
 '17 Years and 11 Months',
 '23 Years and 2 Months',
 '23 Years and 3 Months',
 '23 Years and 4 Months',
 '23 Years and 5 Months',
 '23 Years and 6 Months',
 '8 Years and 4 Months',
 '8 Years and 5 Months',
 '8 Years and 6 Months',
 '8 Years and 8 Months',
 '17 Years and 11 Months',
 '8 Years and 10 Months',
 '8 Years and 11 Months',
 '30 Years and 9 Months',
 '30 Years and 10 Months',
 '30 Years and 11 Months',
 '31 Years and 0 Months',
 '31 Years and 1 Months',
 '31 Years and 2 Months',
 '31 Years and 3 Months',
 '31 Years and 4 Months',
 '4 Years and 5 Months',
 '4 Years and 6 Months',
 '4 Years and 8 Months',
 '4 Years and 9 Months',
 '4 Years and 10 Months',
 '4 Years and 11 Months',
 '5 Years and 0 Months',
 '12 Years and 2 Months',
 '12 Years and 3 Months',
 '17 Years and 11 Months',
 '12 Years and 5 Months',
 '12 Years and 6 Months',
 '12 Years and 7 Months',
 '12 Years and 8 Months',
 '12 Years and 9 Months',
 '32 Years and 1 Months',
 '32 Years and 3 Months',
 '32 Years and 4 Months',
 '32 Years and 5 Months',
 '32 Years and 6 Months',
 '26 Years and 7 Months',
 '26 Years and 8 Months',
 '26 Years and 9 Months',
 '17 Years and 11 Months',
 '26 Years and 11 Months',
 '27 Years and 0 Months',
 '27 Years and 1 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '17 Years and 3 Months',
 '17 Years and 4 Months',
 '17 Years and 5 Months',
 '17 Years and 6 Months',
 '17 Years and 7 Months',
 '17 Years and 8 Months',
 '17 Years and 9 Months',
 '12 Years and 11 Months',
 '13 Years and 0 Months',
 '13 Years and 1 Months',
 '13 Years and 2 Months',
 '17 Years and 11 Months',
 '13 Years and 6 Months',
 '29 Years and 9 Months',
 '17 Years and 11 Months',
 '29 Years and 11 Months',
 '30 Years and 0 Months',
 '17 Years and 11 Months',
 '30 Years and 2 Months',
 '30 Years and 4 Months',
 '25 Years and 7 Months',
 '25 Years and 9 Months',
 '25 Years and 10 Months',
 '25 Years and 11 Months',
 '26 Years and 0 Months',
 '26 Years and 1 Months',
 '26 Years and 2 Months',
 '32 Years and 10 Months',
 '32 Years and 11 Months',
 '33 Years and 0 Months',
 '33 Years and 1 Months',
 '33 Years and 2 Months',
 '33 Years and 3 Months',
 '33 Years and 4 Months',
 '17 Years and 11 Months',
 '26 Years and 2 Months',
 '26 Years and 3 Months',
 '26 Years and 4 Months',
 '26 Years and 5 Months',
 '26 Years and 6 Months',
 '26 Years and 7 Months',
 '26 Years and 8 Months',
 '26 Years and 9 Months',
 '17 Years and 9 Months',
 '17 Years and 10 Months',
 '17 Years and 11 Months',
 '18 Years and 0 Months',
 '18 Years and 1 Months',
 '18 Years and 2 Months',
 '18 Years and 3 Months',
 '18 Years and 4 Months',
 '17 Years and 11 Months',
 '7 Years and 6 Months',
 '7 Years and 7 Months',
 '7 Years and 8 Months',
 '7 Years and 9 Months',
 '7 Years and 10 Months',
 '17 Years and 11 Months',
 '8 Years and 0 Months',
 '11 Years and 2 Months',
 '11 Years and 3 Months',
 '11 Years and 4 Months',
 '11 Years and 5 Months',
 '11 Years and 6 Months',
 '11 Years and 9 Months',
 '28 Years and 3 Months',
 '28 Years and 4 Months',
 '28 Years and 5 Months',
 '28 Years and 6 Months',
 '28 Years and 7 Months',
 '28 Years and 8 Months',
 '28 Years and 10 Months',
 '29 Years and 2 Months',
 '29 Years and 3 Months',
 '29 Years and 4 Months',
 '29 Years and 5 Months',
 '29 Years and 6 Months',
 '29 Years and 7 Months',
 '29 Years and 8 Months',
 '29 Years and 9 Months',
 '18 Years and 11 Months',
 '19 Years and 0 Months',
 '19 Years and 1 Months',
 '19 Years and 2 Months',
 '19 Years and 3 Months',
 '19 Years and 4 Months',
 '19 Years and 5 Months',
 '19 Years and 11 Months',
 '20 Years and 1 Months',
 '20 Years and 3 Months',
 '20 Years and 4 Months',
 '20 Years and 5 Months',
 '20 Years and 6 Months',
 '17 Years and 11 Months',
 '20 Years and 3 Months',
 '20 Years and 4 Months',
 '20 Years and 5 Months',
 '20 Years and 7 Months',
 '20 Years and 8 Months',
 '30 Years and 4 Months',
 '17 Years and 11 Months',
 '30 Years and 6 Months',
 '30 Years and 7 Months',
 '30 Years and 8 Months',
 '30 Years and 9 Months',
 '17 Years and 11 Months',
 '30 Years and 11 Months',
 '28 Years and 7 Months',
 '17 Years and 11 Months',
 '28 Years and 9 Months',
 '28 Years and 11 Months',
 '29 Years and 0 Months',
 '17 Years and 11 Months',
 '29 Years and 2 Months',
 '17 Years and 11 Months',
 '13 Years and 5 Months',
 '13 Years and 6 Months',
 '17 Years and 11 Months',
 '13 Years and 9 Months',
 '13 Years and 10 Months',
 '13 Years and 11 Months',
 '1 Years and 4 Months',
 '1 Years and 5 Months',
 '1 Years and 6 Months',
 '1 Years and 7 Months',
 '1 Years and 8 Months',
 '1 Years and 9 Months',
 '1 Years and 10 Months',
 '1 Years and 11 Months',
 '33 Years and 1 Months',
 '33 Years and 2 Months',
 '33 Years and 3 Months',
 '33 Years and 5 Months',
 '33 Years and 7 Months',
 '25 Years and 9 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '26 Years and 0 Months',
 '26 Years and 1 Months',
 '26 Years and 2 Months',
 '26 Years and 3 Months',
 '26 Years and 4 Months',
 '4 Years and 9 Months',
 '17 Years and 11 Months',
 '4 Years and 11 Months',
 '5 Years and 0 Months',
 '5 Years and 1 Months',
 '5 Years and 2 Months',
 '5 Years and 3 Months',
 '5 Years and 4 Months',
 '31 Years and 7 Months',
 '17 Years and 11 Months',
 '31 Years and 9 Months',
 '31 Years and 10 Months',
 '32 Years and 0 Months',
 '32 Years and 1 Months',
 '32 Years and 2 Months',
 '32 Years and 8 Months',
 '32 Years and 9 Months',
 '32 Years and 10 Months',
 '32 Years and 11 Months',
 '33 Years and 0 Months',
 '33 Years and 1 Months',
 '33 Years and 2 Months',
 '33 Years and 3 Months',
 '8 Years and 9 Months',
 '8 Years and 10 Months',
 '8 Years and 11 Months',
 '9 Years and 0 Months',
 '9 Years and 2 Months',
 '9 Years and 3 Months',
 '17 Years and 11 Months',
 '24 Years and 3 Months',
 '24 Years and 4 Months',
 '24 Years and 6 Months',
 '24 Years and 7 Months',
 '24 Years and 8 Months',
 '24 Years and 9 Months',
 '24 Years and 10 Months',
 '5 Years and 9 Months',
 '5 Years and 10 Months',
 '5 Years and 11 Months',
 '6 Years and 1 Months',
 '6 Years and 2 Months',
 '6 Years and 3 Months',
 '17 Years and 11 Months',
 '17 Years and 11 Months',
 '19 Years and 4 Months',
 '19 Years and 5 Months',
 '19 Years and 6 Months',
 '19 Years and 7 Months',
 '19 Years and 8 Months',
 '19 Years and 9 Months',
 '19 Years and 10 Months',
 '22 Years and 4 Months',
 '22 Years and 5 Months',
 '22 Years and 6 Months',
 '17 Years and 11 Months',
 '22 Years and 9 Months',
 '22 Years and 10 Months',
 '22 Years and 11 Months',
 '16 Years and 4 Months',
 '16 Years and 5 Months',
 '16 Years and 6 Months',
 '16 Years and 7 Months',
 '16 Years and 8 Months',
 '16 Years and 10 Months',
 '16 Years and 11 Months',
 '22 Years and 9 Months',
 '22 Years and 10 Months',
 '22 Years and 11 Months',
 '17 Years and 11 Months',
 '23 Years and 1 Months',
 '23 Years and 2 Months',
 '23 Years and 3 Months',
 '17 Years and 11 Months',
 '21 Years and 8 Months',
 '21 Years and 9 Months',
 '21 Years and 10 Months',
 '21 Years and 11 Months',
 '22 Years and 0 Months',
 '17 Years and 11 Months',
 '22 Years and 2 Months',
 '21 Years and 7 Months',
 '17 Years and 11 Months',
 '21 Years and 10 Months',
 '21 Years and 11 Months',
 '22 Years and 0 Months',
 '22 Years and 1 Months',
 '22 Years and 2 Months',
 '20 Years and 2 Months',
 '20 Years and 3 Months',
 '20 Years and 4 Months',
 '17 Years and 11 Months',
 '20 Years and 6 Months',
 '20 Years and 7 Months',

In [34]:
year = []
upgrade = 0

for item in list1:
    year.append(list1[upgrade][0])
    upgrade =+ 1

In [35]:
split_texts = [text.split() for text in list1]

In [36]:
split_texts[3][0]

'22'

In [37]:
year = []
upgrade = 0

for item in split_texts:
    year.append(split_texts[upgrade][0])
    upgrade = upgrade + 1

In [ ]:
year

In [38]:
months = []
month_upgrade = 0

for item in split_texts:
    months.append(split_texts[month_upgrade][3])
    month_upgrade = month_upgrade + 1

In [ ]:
months

In [ ]:
months_list

In [44]:
months = [int(item) for item in months]

In [42]:
int_year

[22,
 17,
 22,
 22,
 22,
 22,
 22,
 17,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 17,
 17,
 18,
 18,
 18,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 17,
 17,
 32,
 32,
 17,
 32,
 32,
 30,
 30,
 30,
 30,
 30,
 31,
 31,
 31,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 21,
 17,
 26,
 26,
 26,
 26,
 17,
 26,
 27,
 19,
 19,
 19,
 19,
 19,
 19,
 17,
 25,
 25,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 27,
 27,
 27,
 27,
 27,
 27,
 8,
 9,
 9,
 9,
 9,
 9,
 17,
 9,
 18,
 18,
 18,
 18,
 18,
 17,
 18,
 18,
 16,
 16,
 17,
 17,
 17,
 17,
 17,
 17,
 29,
 29,
 29,
 17,
 29,
 17,
 29,
 29,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 27,
 18,
 18,
 17,
 18,
 17,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 32,
 32,
 32,
 33,
 33,
 17,
 17,
 33,
 12,
 12,
 12,
 12,
 12,
 17,
 12,
 17,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 17,
 18,
 18,
 17,
 17,
 18,
 13,
 17,
 17,
 13,
 14,
 14,
 14,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 30,
 30,
 30,
 30,
 30,
 17,
 30,
 17,
 8,
 8,
 8,
 9,
 9,
 17,
 9,
 18,
 18,
 18,
 18,
 18,
 18,
 18,
 17,
 18,
 18,
 18,
 19,
 19,
 19,
 19,
 19,
 8,
 8,
 8,
 9,
 9,
 9,
 9,
 13,
 13,
 13,
 17,
 13,
 13,
 13,
 13,
 21,
 21,
 21,
 21,
 21,
 21,
 17,
 22,
 25,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 17,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 27,
 28,
 28,
 28,
 28,
 7,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 17,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 17,
 10,
 11,
 11,
 11,
 11,
 11,
 30,
 30,
 30,
 31,
 31,
 31,
 19,
 19,
 19,
 19,
 19,
 20,
 20,
 17,
 10,
 10,
 17,
 10,
 10,
 17,
 11,
 13,
 14,
 14,
 14,
 14,
 14,
 20,
 20,
 20,
 20,
 21,
 21,
 21,
 0,
 0,
 0,
 17,
 0,
 0,
 0,
 17,
 31,
 31,
 31,
 31,
 31,
 32,
 32,
 32,
 16,
 17,
 17,
 17,
 17,
 17,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 12,
 12,
 12,
 12,
 17,
 13,
 13,
 13,
 27,
 27,
 27,
 27,
 27,
 27,
 11,
 11,
 11,
 11,
 11,
 11,
 17,
 17,
 24,
 24,
 24,
 25,
 25,
 25,
 17,
 17,
 17,
 17,
 18,
 18,
 18,
 12,
 12,
 12,
 13,
 17,
 13,
 17,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 19,
 19,
 19,
 19,
 19,
 19,
 17,
 31,
 31,
 31,
 31,
 31,
 31,
 17,
 30,
 30,
 30,
 31,
 31,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 13,
 13,
 13,
 13,
 13,
 17,
 13,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 17,
 16,
 16,
 16,
 16,
 16,
 16,
 22,
 23,
 17,
 23,
 23,
 23,
 23,
 23,
 8,
 8,
 8,
 8,
 17,
 8,
 8,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 12,
 12,
 17,
 12,
 12,
 12,
 12,
 12,
 32,
 32,
 32,
 32,
 32,
 26,
 26,
 26,
 17,
 26,
 27,
 27,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 12,
 13,
 13,
 13,
 17,
 13,
 29,
 17,
 29,
 30,
 17,
 30,
 30,
 25,
 25,
 25,
 25,
 26,
 26,
 26,
 32,
 32,
 33,
 33,
 33,
 33,
 33,
 17,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 17,
 17,
 17,
 18,
 18,
 18,
 18,
 18,
 17,
 7,
 7,
 7,
 7,
 7,
 17,
 8,
 11,
 11,
 11,
 11,
 11,
 11,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 29,
 18,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 20,
 20,
 20,
 20,
 20,
 17,
 20,
 20,
 20,
 20,
 20,
 30,
 17,
 30,
 30,
 30,
 30,
 17,
 30,
 28,
 17,
 28,
 28,
 29,
 17,
 29,
 17,
 13,
 13,
 17,
 13,
 13,
 13,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 33,
 33,
 33,
 33,
 33,
 25,
 17,
 17,
 26,
 26,
 26,
 26,
 26,
 4,
 17,
 4,
 5,
 5,
 5,
 5,
 5,
 31,
 17,
 31,
 31,
 32,
 32,
 32,
 32,
 32,
 32,
 32,
 33,
 33,
 33,
 33,
 8,
 8,
 8,
 9,
 9,
 9,
 17,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 5,
 5,
 5,
 6,
 6,
 6,
 17,
 17,
 19,
 19,
 19,
 19,
 19,
 19,
 19,
 22,
 22,
 22,
 17,
 22,
 22,
 22,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 22,
 22,
 22,
 17,
 23,
 23,
 23,
 17,
 21,
 21,
 21,
 21,
 22,
 17,
 22,
 21,
 17,
 21,
 21,
 22,
 22,
 22,
 20,
 20,
 20,
 17,
 20,
 20,
 20,
 20,
 17,
 28,
 28,
 28,
 28,
 28,
 28,
 12,
 12,
 17,
 17,
 12,
 12,
 12,
 17,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 20,
 20,
 20,
 20,
 20,
 20,
 17,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 13,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 17,
 5,
 5,
 5,
 5,
 5,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 27,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 15,
 15,
 15,
 15,
 15,
 15,
 15,
 16,
 16,
 16,
 16,
 16,
 16,
 16,
 30,
 30,
 30,
 31,
 31,
 31,
 31,
 31,
 9,
 9,
 9,
 17,
 9,
 9,
 9,
 27,
 27,
 27,
 27,
 17,
 27,
 27,
 27,
 27,
 27,
 17,
 28,
 17,
 28,
 28,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 17,
 18,
 18,
 17,
 18,
 18,
 18,
 17,
 18,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 17,
 7,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 5,
 5,
 5,
 5,
 17,
 6,
 6,
 16,
 16,
 17,
 17,
 16,
 17,
 17,
 17,
 26,
 26,
 17,
 27,
 27,
 27,
 27,
 27,
 17,
 11,
 12,
 12,
 12,
 17,
 12,
 25,
 26,
 26,
 26,
 26,
 26,
 26,
 26,
 28,
 28,
 29,
 29,
 17,
 17,
 27,
 17,
 28,
 28,
 17,
 17,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 31,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 21,
 21,
 17,
 21,
 21,
 21,
 17,
 21,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 22,
 22,
 22,
 23,
 23,
 23,
 23,
 23,
 13,
 13,
 ...]

In [40]:
months_list = [y * 12 for y in int_year]

In [43]:
months_list

[264,
 204,
 264,
 264,
 264,
 264,
 264,
 204,
 312,
 312,
 312,
 312,
 324,
 324,
 324,
 204,
 204,
 216,
 216,
 216,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 360,
 360,
 360,
 360,
 372,
 372,
 372,
 372,
 204,
 204,
 384,
 384,
 204,
 384,
 384,
 360,
 360,
 360,
 360,
 360,
 372,
 372,
 372,
 252,
 252,
 252,
 252,
 252,
 252,
 252,
 252,
 204,
 312,
 312,
 312,
 312,
 204,
 312,
 324,
 228,
 228,
 228,
 228,
 228,
 228,
 204,
 300,
 300,
 300,
 300,
 300,
 300,
 300,
 312,
 312,
 312,
 324,
 324,
 324,
 324,
 324,
 324,
 96,
 108,
 108,
 108,
 108,
 108,
 204,
 108,
 216,
 216,
 216,
 216,
 216,
 204,
 216,
 216,
 192,
 192,
 204,
 204,
 204,
 204,
 204,
 204,
 348,
 348,
 348,
 204,
 348,
 204,
 348,
 348,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 84,
 324,
 324,
 324,
 324,
 324,
 324,
 324,
 324,
 216,
 216,
 204,
 216,
 204,
 216,
 216,
 228,
 228,
 228,
 228,
 228,
 228,
 228,
 384,
 384,
 384,
 396,
 396,
 204,
 204,
 396,
 144,
 144,
 144,
 144,
 144,
 204,
 144,
 204,
 144,
 144,
 144,
 144,
 144,
 144,
 144,
 204,
 216,
 216,
 204,
 204,
 216,
 156,
 204,
 204,
 156,
 168,
 168,
 168,
 228,
 228,
 228,
 228,
 228,
 228,
 228,
 228,
 360,
 360,
 360,
 360,
 360,
 204,
 360,
 204,
 96,
 96,
 96,
 108,
 108,
 204,
 108,
 216,
 216,
 216,
 216,
 216,
 216,
 216,
 204,
 216,
 216,
 216,
 228,
 228,
 228,
 228,
 228,
 96,
 96,
 96,
 108,
 108,
 108,
 108,
 156,
 156,
 156,
 204,
 156,
 156,
 156,
 156,
 252,
 252,
 252,
 252,
 252,
 252,
 204,
 264,
 300,
 300,
 300,
 300,
 300,
 312,
 312,
 312,
 204,
 156,
 156,
 156,
 156,
 156,
 156,
 156,
 324,
 336,
 336,
 336,
 336,
 84,
 84,
 96,
 96,
 96,
 96,
 96,
 96,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 204,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 204,
 120,
 132,
 132,
 132,
 132,
 132,
 360,
 360,
 360,
 372,
 372,
 372,
 228,
 228,
 228,
 228,
 228,
 240,
 240,
 204,
 120,
 120,
 204,
 120,
 120,
 204,
 132,
 156,
 168,
 168,
 168,
 168,
 168,
 240,
 240,
 240,
 240,
 252,
 252,
 252,
 0,
 0,
 0,
 204,
 0,
 0,
 0,
 204,
 372,
 372,
 372,
 372,
 372,
 384,
 384,
 384,
 192,
 204,
 204,
 204,
 204,
 204,
 144,
 144,
 144,
 144,
 144,
 144,
 144,
 156,
 144,
 144,
 144,
 144,
 204,
 156,
 156,
 156,
 324,
 324,
 324,
 324,
 324,
 324,
 132,
 132,
 132,
 132,
 132,
 132,
 204,
 204,
 288,
 288,
 288,
 300,
 300,
 300,
 204,
 204,
 204,
 204,
 216,
 216,
 216,
 144,
 144,
 144,
 156,
 204,
 156,
 204,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 120,
 228,
 228,
 228,
 228,
 228,
 228,
 204,
 372,
 372,
 372,
 372,
 372,
 372,
 204,
 360,
 360,
 360,
 372,
 372,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 156,
 156,
 156,
 156,
 156,
 204,
 156,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 60,
 156,
 156,
 156,
 156,
 156,
 156,
 156,
 156,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 204,
 192,
 192,
 192,
 192,
 192,
 192,
 264,
 276,
 204,
 276,
 276,
 276,
 276,
 276,
 96,
 96,
 96,
 96,
 204,
 96,
 96,
 360,
 360,
 360,
 372,
 372,
 372,
 372,
 372,
 48,
 48,
 48,
 48,
 48,
 48,
 60,
 144,
 144,
 204,
 144,
 144,
 144,
 144,
 144,
 384,
 384,
 384,
 384,
 384,
 312,
 312,
 312,
 204,
 312,
 324,
 324,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 144,
 156,
 156,
 156,
 204,
 156,
 348,
 204,
 348,
 360,
 204,
 360,
 360,
 300,
 300,
 300,
 300,
 312,
 312,
 312,
 384,
 384,
 396,
 396,
 396,
 396,
 396,
 204,
 312,
 312,
 312,
 312,
 312,
 312,
 312,
 312,
 204,
 204,
 204,
 216,
 216,
 216,
 216,
 216,
 204,
 84,
 84,
 84,
 84,
 84,
 204,
 96,
 132,
 132,
 132,
 132,
 132,
 132,
 336,
 336,
 336,
 336,
 336,
 336,
 336,
 348,
 348,
 348,
 348,
 348,
 348,
 348,
 348,
 216,
 228,
 228,
 228,
 228,
 228,
 228,
 228,
 240,
 240,
 240,
 240,
 240,
 204,
 240,
 240,
 240,
 240,
 240,
 360,
 204,
 360,
 360,
 360,
 360,
 204,
 360,
 336,
 204,
 336,
 336,
 348,
 204,
 348,
 204,
 156,
 156,
 204,
 156,
 156,
 156,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 396,
 396,
 396,
 396,
 396,
 300,
 204,
 204,
 312,
 312,
 312,
 312,
 312,
 48,
 204,
 48,
 60,
 60,
 60,
 60,
 60,
 372,
 204,
 372,
 372,
 384,
 384,
 384,
 384,
 384,
 384,
 384,
 396,
 396,
 396,
 396,
 96,
 96,
 96,
 108,
 108,
 108,
 204,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 60,
 60,
 60,
 72,
 72,
 72,
 204,
 204,
 228,
 228,
 228,
 228,
 228,
 228,
 228,
 264,
 264,
 264,
 204,
 264,
 264,
 264,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 264,
 264,
 264,
 204,
 276,
 276,
 276,
 204,
 252,
 252,
 252,
 252,
 264,
 204,
 264,
 252,
 204,
 252,
 252,
 264,
 264,
 264,
 240,
 240,
 240,
 204,
 240,
 240,
 240,
 240,
 204,
 336,
 336,
 336,
 336,
 336,
 336,
 144,
 144,
 204,
 204,
 144,
 144,
 144,
 204,
 180,
 180,
 180,
 180,
 180,
 180,
 180,
 240,
 240,
 240,
 240,
 240,
 240,
 204,
 144,
 144,
 144,
 144,
 144,
 144,
 144,
 156,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 48,
 204,
 60,
 60,
 60,
 60,
 60,
 312,
 312,
 312,
 312,
 312,
 312,
 312,
 324,
 12,
 12,
 12,
 12,
 12,
 12,
 24,
 180,
 180,
 180,
 180,
 180,
 180,
 180,
 192,
 192,
 192,
 192,
 192,
 192,
 192,
 360,
 360,
 360,
 372,
 372,
 372,
 372,
 372,
 108,
 108,
 108,
 204,
 108,
 108,
 108,
 324,
 324,
 324,
 324,
 204,
 324,
 324,
 324,
 324,
 324,
 204,
 336,
 204,
 336,
 336,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 204,
 216,
 216,
 204,
 216,
 216,
 216,
 204,
 216,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 204,
 84,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 60,
 60,
 60,
 60,
 204,
 72,
 72,
 192,
 192,
 204,
 204,
 192,
 204,
 204,
 204,
 312,
 312,
 204,
 324,
 324,
 324,
 324,
 324,
 204,
 132,
 144,
 144,
 144,
 204,
 144,
 300,
 312,
 312,
 312,
 312,
 312,
 312,
 312,
 336,
 336,
 348,
 348,
 204,
 204,
 324,
 204,
 336,
 336,
 204,
 204,
 372,
 372,
 372,
 372,
 372,
 372,
 372,
 372,
 132,
 132,
 132,
 132,
 132,
 132,
 132,
 132,
 252,
 252,
 204,
 252,
 252,
 252,
 204,
 252,
 288,
 288,
 288,
 288,
 288,
 288,
 288,
 264,
 264,
 264,
 276,
 276,
 276,
 276,
 276,
 156,
 156,
 ...]

In [45]:
total_months = [x + y for x, y in zip(months, months_list)]

In [46]:
train_df['total_month'] = total_months

In [48]:
train_df.drop('Credit_History_Age', axis = 1)

,Customer_ID,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,...,Credit_Score,Debt Consolidation Loan,Personal Loan,Student Loan,Credit-Builder Loan,Payday Loan,Mortgage Loan,Auto Loan,Home Equity Loan,total_month
0,1.0,1,23.0,0,19114.12,1824.843333,3.0,4.0,3.0,4.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,265
1,1.0,2,23.0,0,19114.12,1824.843333,3.0,4.0,3.0,4.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,215
2,1.0,3,-500.0,0,19114.12,1824.843333,3.0,4.0,3.0,4.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,267
3,1.0,4,23.0,0,19114.12,1824.843333,3.0,4.0,3.0,4.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,268
4,1.0,5,23.0,0,19114.12,1824.843333,3.0,4.0,3.0,4.0,...,2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,11660.0,4,25.0,11,39628.99,3359.415833,4.0,6.0,7.0,2.0,...,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,378
99996,11660.0,5,25.0,11,39628.99,3359.415833,4.0,6.0,7.0,2.0,...,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,379
99997,11660.0,6,25.0,11,39628.99,3359.415833,4.0,6.0,5729.0,2.0,...,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,380
99998,11660.0,7,25.0,11,39628.99,3359.415833,4.0,6.0,7.0,2.0,...,1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,381
99999,11660.0,8,25.0,11,39628.99,3359.415833,4.0,6.0,7.0,2.0,...,0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,382

In [59]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86706 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               86706 non-null  float64
 1   Month                     86706 non-null  int64
 2   Age                       86706 non-null  float64
 3   Occupation                86706 non-null  int64
 4   Annual_Income             86706 non-null  float64
 5   Monthly_Inhand_Salary     86706 non-null  float64
 6   Num_Bank_Accounts         86706 non-null  float64
 7   Num_Credit_Card           86706 non-null  float64
 8   Interest_Rate             86706 non-null  float64
 9   Num_of_Loan               86706 non-null  float64
 10  Delay_from_due_date       86706 non-null  float64
 11  Num_of_Delayed_Payment    86706 non-null  float64
 12  Changed_Credit_Limit      86706 non-null  float64
 13  Num_Credit_Inquiries      86706 non-null  float64
 14  Credit_Mix                86706 non-null  int64
 15  Outstanding_Debt          86706 non-null  float64
 16  Credit_Utilization_Ratio  86706 non-null  float64
 17  Payment_of_Min_Amount     86706 non-null  int64
 18  Total_EMI_per_month       86706 non-null  float64
 19  Amount_invested_monthly   86706 non-null  float64
 20  Payment_Behaviour         86706 non-null  int64
 21  Monthly_Balance           86706 non-null  float64
 22  Credit_Score              86706 non-null  int64
 23  Debt Consolidation Loan   86706 non-null  float64
 24  Personal Loan             86706 non-null  float64
 25  Student Loan              86706 non-null  float64
 26  Credit-Builder Loan       86706 non-null  float64
 27  Payday Loan               86706 non-null  float64
 28  Mortgage Loan             86706 non-null  float64
 29  Auto Loan                 86706 non-null  float64
 30  Home Equity Loan          86706 non-null  float64
 31  total_month               86706 non-null  int64
dtypes: float64(25), int64(7)
memory usage: 21.8 MB

In [61]:
# define dataset
X, y = train_df.drop("Credit_Score",axis=1).values , train_df["Credit_Score"]

In [62]:
y.value_counts(normalize=True)

Credit_Score
1    0.530067
0    0.292044
2    0.177888
Name: proportion, dtype: float64

# MODEL 1 (Best Performer)

In [117]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Splitting dataset into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [118]:
# Predictions
y_pred = rf_classifier.predict(X_test)

In [119]:
# Evaluation
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.81      0.80      5049
           1       0.81      0.82      0.81      9160
           2       0.77      0.71      0.74      3133

    accuracy                           0.80     17342
   macro avg       0.79      0.78      0.78     17342
weighted avg       0.79      0.80      0.79     17342

Accuracy Score: 0.7954099873140353

# Model 2 XGBoost

In [120]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Initialize and train the XGBoost Classifier
xgb_classifier = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, objective='multi:softprob', ...)

In [121]:
# Predictions
y_pred = xgb_classifier.predict(X_test)

In [122]:

# Evaluation
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           0       0.76      0.73      0.75      5049
           1       0.77      0.79      0.78      9160
           2       0.70      0.68      0.69      3133

    accuracy                           0.76     17342
   macro avg       0.75      0.74      0.74     17342
weighted avg       0.76      0.76      0.76     17342

Accuracy Score: 0.7571214392803598

# Model 3 KNN Classifier

In [123]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

# Initialize KNN Classifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the data
knn_classifier.fit(X_train, y_train)

# Predictions
y_pred_knn = knn_classifier.predict(X_test)

# Evaluation
print("KNN Classifier Report:\n", classification_report(y_test, y_pred_knn))
print("KNN Accuracy Score:", accuracy_score(y_test, y_pred_knn))

KNN Classifier Report:
               precision    recall  f1-score   support

           0       0.71      0.76      0.74      5049
           1       0.76      0.77      0.76      9160
           2       0.70      0.60      0.65      3133

    accuracy                           0.74     17342
   macro avg       0.72      0.71      0.72     17342
weighted avg       0.73      0.74      0.73     17342

KNN Accuracy Score: 0.7354976357974858